import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:wheater_app/screen/utils/constants/colors.dart';

class TextThemes {
  TextThemes._();

  static TextTheme darkTextTheme = TextTheme(
    displayLarge: GoogleFonts.poppins(
      fontSize: 57.0,
      fontWeight: FontWeight.w400,
      letterSpacing: -0.25,
      height: 64.0 / 57.0,
      color: AppColors.lightTextPrimary,
    ),
    displayMedium: GoogleFonts.poppins(
      fontSize: 45.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.0,
      height: 52.0 / 45.0,
      color: AppColors.lightTextPrimary,
    ),
    displaySmall: GoogleFonts.poppins(
      fontSize: 36.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.0,
      height: 44.0 / 36.0,
      color: AppColors.lightTextPrimary,
    ),
    headlineLarge: GoogleFonts.poppins(
      fontSize: 32.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.0,
      height: 40.0 / 32.0,
      color: AppColors.lightTextPrimary,
    ),
    headlineMedium: GoogleFonts.poppins(
      fontSize: 28.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.0,
      height: 36.0 / 28.0,
      color: AppColors.lightTextPrimary,
    ),
    headlineSmall: GoogleFonts.poppins(
      fontSize: 24.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.0,
      height: 32.0 / 24.0,
      color: AppColors.lightTextPrimary,
    ),
    titleLarge: GoogleFonts.poppins(
      fontSize: 22.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.0,
      height: 28.0 / 22.0,
      color: AppColors.lightTextPrimary,
    ),
    titleMedium: GoogleFonts.poppins(
      fontSize: 16.0,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.15,
      height: 24.0 / 16.0,
      color: AppColors.lightTextPrimary,
    ),
    titleSmall: GoogleFonts.poppins(
      fontSize: 14.0,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.1,
      height: 20.0 / 14.0,
      color: AppColors.lightTextPrimary,
    ),
    bodyLarge: GoogleFonts.poppins(
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.5,
      height: 24.0 / 16.0,
      color: AppColors.lightTextPrimary,
    ),
    bodyMedium: GoogleFonts.poppins(
      fontSize: 14.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.25,
      height: 20.0 / 14.0,
      color: AppColors.lightTextPrimary,
    ),
    bodySmall: GoogleFonts.poppins(
      fontSize: 12.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.4,
      height: 16.0 / 12.0,
      color: AppColors.lightTextPrimary,
    ),
    labelLarge: GoogleFonts.poppins(
      fontSize: 14.0,
      fontWeight: FontWeight.w700,
      letterSpacing: 0.1,
      height: 20.0 / 14.0,
      color: AppColors.lightTextPrimary,
    ),
    labelMedium: GoogleFonts.poppins(
      fontSize: 12.0,
      fontWeight: FontWeight.w700,
      letterSpacing: 0.5,
      height: 16.0 / 12.0,
      color: AppColors.lightTextPrimary,
    ),
    labelSmall: GoogleFonts.poppins(
      fontSize: 11.0,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.5,
      height: 16.0 / 11.0,
      color: AppColors.lightTextPrimary,
    ),
  );

  static TextTheme lightTextTheme = TextTheme(
    displayLarge: GoogleFonts.poppins(
      fontSize: 57.0,
      fontWeight: FontWeight.w400,
      letterSpacing: -0.25,
      height: 64.0 / 57.0,
      color: AppColors.darkTextPrimary,
    ),
    displayMedium: GoogleFonts.poppins(
      fontSize: 45.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.0,
      height: 52.0 / 45.0,
      color: AppColors.darkTextPrimary,
    ),
    displaySmall: GoogleFonts.poppins(
      fontSize: 36.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.0,
      height: 44.0 / 36.0,
      color: AppColors.darkTextPrimary,
    ),
    headlineLarge: GoogleFonts.poppins(
      fontSize: 32.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.0,
      height: 40.0 / 32.0,
      color: AppColors.darkTextPrimary,
    ),
    headlineMedium: GoogleFonts.poppins(
      fontSize: 28.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.0,
      height: 36.0 / 28.0,
      color: AppColors.darkTextPrimary,
    ),
    headlineSmall: GoogleFonts.poppins(
      fontSize: 24.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.0,
      height: 32.0 / 24.0,
      color: AppColors.darkTextPrimary,
    ),
    titleLarge: GoogleFonts.poppins(
      fontSize: 22.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.0,
      height: 28.0 / 22.0,
      color: AppColors.darkTextPrimary,
    ),
    titleMedium: GoogleFonts.poppins(
      fontSize: 16.0,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.15,
      height: 24.0 / 16.0,
      color: AppColors.darkTextPrimary,
    ),
    titleSmall: GoogleFonts.poppins(
      fontSize: 14.0,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.1,
      height: 20.0 / 14.0,
      color: AppColors.darkTextPrimary,
    ),
    bodyLarge: GoogleFonts.poppins(
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.5,
      height: 24.0 / 16.0,
      color: AppColors.darkTextPrimary,
    ),
    bodyMedium: GoogleFonts.poppins(
      fontSize: 14.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.25,
      height: 20.0 / 14.0,
      color: AppColors.darkTextPrimary,
    ),
    bodySmall: GoogleFonts.poppins(
      fontSize: 12.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.4,
      height: 16.0 / 12.0,
      color: AppColors.darkTextPrimary,
    ),
    labelLarge: GoogleFonts.poppins(
      fontSize: 14.0,
      fontWeight: FontWeight.w700,
      letterSpacing: 0.1,
      height: 20.0 / 14.0,
      color: AppColors.darkTextPrimary,
    ),
    labelMedium: GoogleFonts.poppins(
      fontSize: 12.0,
      fontWeight: FontWeight.w700,
      letterSpacing: 0.5,
      height: 16.0 / 12.0,
      color: AppColors.darkTextPrimary,
    ),
    labelSmall: GoogleFonts.poppins(
      fontSize: 11.0,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.5,
      height: 16.0 / 11.0,
      color: AppColors.darkTextPrimary,
    ),
  );
}
